//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFLWatcher.Models {
    using System;
    using System.Collections.Generic;
    
    public partial class YouTubeSearchFilter
    {
        public int Id { get; set; }
        public string SearchTerm { get; set; }
        public int MaxResults { get; set; }
        public string IdKind { get; set; }
    }
}
